---
- hosts: all
  become: yes
  tasks:
  - name: download amazon agent
    get_url: url=https://s3.us-east-1.amazonaws.com/amazoncloudwatch-agent-us-east-1/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm dest=/tmp/amazon-cloudwatch-agent.rpm
  - name: Install package.
    yum:
      name: /tmp/amazon-cloudwatch-agent.rpm
      state: present
  - name: If follow=no, /path/to/link will become a file and be overwritten by contents of foo.conf
    ansible.builtin.copy:
      src: /aws_cloudwatch_config.config
      dest: /aws_cloudwatch_config.config  # link to /path/to/file
      follow: no

  - name: Start the agent
    shell: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/aws_cloudwatch_config.config -s

